### ISSUE TITLE
Make keep the default!

### ISSUE THREAD

**Issue by oderwat** [smittytone/imageprep#1]
I would highly recommend that you make "keep" the default and use a flag for the actual removal.

For AI purposes, it would be cool if you had a padding variant that repeats the last one pixel row/col at the border of the image into that direction. This also looks surprisingly good for a human. Another nice variation is to choose the color base on the average color of the border pixels, so you get a light or dark color matching background instead of the harsh padding.

It would be nice to be able to set the JPEG compression factor too.

Another option could be if you want to keep metadata. I don't know if the libraries you use, offer this, though.

**Comment by smittytone** [comment]
Interesting suggestions, thanks. I may take a look as some of those.

**Comment by smittytone** [comment]
A new version coming very shortly will make keep the default and allow you to set the JPEG compression level.
